# https://docs.rs/chrono/0.4.23/chrono/

[package]
name = "swaybar_status"
version = "0.0.0"

[dependencies]
chrono = "0.4.23"
notify-rust = "4.10.0"

[profile.release]
opt-level = 'z' # Optimize for size
lto = true
codegen-units = 1
strip = true
